#!/usr/bin/env python3
"""Write tables.bend from the pinned UCD. Run from anywhere: python3 unicode/gen.py"""
import os
import urllib.request

VERSION = "17.0.0"
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "ucd", VERSION)
FILES = [
    "UnicodeData.txt",
    "CaseFolding.txt",
    "DerivedNormalizationProps.txt",
    "DerivedCoreProperties.txt",
    "auxiliary/GraphemeBreakProperty.txt",
    "emoji/emoji-data.txt",
    "auxiliary/GraphemeBreakTest.txt",
    "NormalizationTest.txt",
]


def fetch():
    os.makedirs(CACHE, exist_ok=True)
    for f in FILES:
        path = os.path.join(CACHE, os.path.basename(f))
        if not os.path.exists(path):
            url = f"https://www.unicode.org/Public/{VERSION}/ucd/{f}"
            urllib.request.urlretrieve(url, path)


def ucd(name):
    return open(os.path.join(CACHE, name), encoding="utf-8")


def props(name, prop=None):
    """code point -> [fields after the first], for `a..b ; v ; ...` files.
    Files that list several properties per code point need prop to pick one."""
    out = {}
    for line in ucd(name):
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        if prop and f[1] != prop:
            continue
        a, _, b = f[0].partition("..")
        for c in range(int(a, 16), int(b or a, 16) + 1):
            out[c] = f[1:]
    return out


def unicode_data():
    gc, ccc, dec = {}, {}, {}
    rows = [l.split(";") for l in ucd("UnicodeData.txt").read().splitlines()]
    i = 0
    while i < len(rows):
        f = rows[i]
        cp = int(f[0], 16)
        end = cp
        if f[1].endswith("First>"):
            end = int(rows[i + 1][0], 16)
            i += 1
        for c in range(cp, end + 1):
            gc[c] = f[2]
        if f[3] != "0":
            ccc[cp] = int(f[3])
        if f[5] and not f[5].startswith("<"):
            dec[cp] = [int(x, 16) for x in f[5].split()]
        i += 1
    return gc, ccc, dec


def s(cps):
    return '"' + "".join(f"\\u{{{c:X}}}" for c in cps) + '"'


class Tree:
    """Emit a balanced decision tree over sorted ranges as Bend defs, leaves first."""

    def __init__(self, name, params, key, ret):
        self.name, self.params, self.key, self.ret = name, params, key, ret
        self.defs, self.n = [], 0

    def build(self, ranges):
        # ranges: sorted, contiguous [(start, leaf_expr)] from 0.
        return self.node(ranges, 0, len(ranges) - 1)

    def node(self, r, lo, hi):
        if lo == hi:
            return r[lo][1]
        mid = (lo + hi + 1) // 2
        left, right = self.node(r, lo, mid - 1), self.node(r, mid, hi)
        name = f"{self.name}.n{self.n}"
        self.n += 1
        ps = ", ".join(f"+{p}: U32" for p in self.params)
        self.defs.append(
            f"def {name}(lt: Bool, {ps}) -> {self.ret}:\n  match lt:\n"
            f"    case True{{}}:\n      {left}\n    case False{{}}:\n      {right}\n"
        )
        args = ", ".join(self.params)
        return f"{name}(U32.is_lt({self.key}, {r[mid][0]}), {args})"

    def emit(self, ranges, top):
        root = self.build(ranges)
        ps = ", ".join(f"+{p}: U32" for p in self.params)
        return "\n".join(self.defs) + f"\ndef {top}({ps}) -> {self.ret}:\n  {root}\n"


def ranges(value, keys, gap):
    """Merge code points into [(start, leaf)]: value(c) for keys, gap elsewhere."""
    out = [(0, gap)]

    def push(start, v):
        if out[-1][1] == v:
            return
        if out[-1][0] == start:
            out[-1] = (start, v)
        else:
            out.append((start, v))

    prev = -1
    for c in sorted(keys):
        if c != prev + 1:
            push(prev + 1, gap)
        push(c, value(c))
        prev = c
    if prev < 0x10FFFF:
        push(prev + 1, gap)
    return out


GCB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
       "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"]
INCB = {"Consonant": 1, "Extend": 2, "Linker": 3}


def main():
    fetch()
    gc, ccc, dec = unicode_data()
    one = "SCon{Chr{c}, SNil{}}"
    parts = [f"# Generated by gen.py from UCD {VERSION}. Do not edit.\nimport Base\n"]

    parts.append(Tree("gc", ["c"], "c", "String").emit(
        ranges(lambda c: f'"{gc[c]}"', gc, '"Cn"'), "gc"))

    parts.append(Tree("ccc", ["c"], "c", "U32").emit(
        ranges(lambda c: str(ccc[c]), ccc, "0"), "ccc"))

    def full(c):
        return [y for x in dec[c] for y in (full(x) if x in dec else [x])]

    parts.append(Tree("dec", ["c"], "c", "String").emit(
        ranges(lambda c: s(full(c)), dec, one), "dec"))

    excl = set(props("DerivedNormalizationProps.txt", "Full_Composition_Exclusion"))
    pairs = {}
    for c, d in dec.items():
        if len(d) == 2 and c not in excl:
            pairs.setdefault(d[1], {})[d[0]] = c
    subs = []
    for b in sorted(pairs):
        t = Tree(f"comp.b{b}", ["a"], "a", "Maybe<&2, U32>")
        subs.append(t.emit(ranges(lambda a: f"Some{{{pairs[b][a]}}}", pairs[b], "None{}"),
                           f"comp.b{b}"))
    parts += subs
    parts.append(Tree("comp", ["b", "a"], "b", "Maybe<&2, U32>").emit(
        ranges(lambda b: f"comp.b{b}(a)", pairs, "None{}"), "comp"))

    fold = {}
    for line in ucd("CaseFolding.txt"):
        f = [x.strip() for x in line.split("#")[0].split(";")]
        if len(f) > 2 and f[1] in ("C", "F"):
            fold[int(f[0], 16)] = [int(x, 16) for x in f[2].split()]
    parts.append(Tree("fold", ["c"], "c", "String").emit(
        ranges(lambda c: s(fold[c]), fold, one), "fold"))

    gb = {c: GCB.index(v[0]) for c, v in props("GraphemeBreakProperty.txt").items()}
    for c in props("emoji-data.txt", "Extended_Pictographic"):
        gb[c] = gb.get(c, 0) | 16
    for c, v in props("DerivedCoreProperties.txt", "InCB").items():
        gb[c] = gb.get(c, 0) | (INCB[v[1]] << 5)
    parts.append(Tree("gb", ["c"], "c", "U32").emit(
        ranges(lambda c: str(gb[c]), gb, "0"), "gb"))

    with open(os.path.join(HERE, "tables.bend"), "w") as out:
        out.write("\n".join(parts))


if __name__ == "__main__":
    main()
