import Base
import ./LAWS.bend as Laws

def Laws.category_upper():
  {==}

def Laws.category_digit():
  {==}

def Laws.category_han():
  {==}

def Laws.category_unassigned():
  {==}

def Laws.category_surrogate():
  {==}

def Laws.ccc_starter():
  {==}

def Laws.ccc_acute():
  {==}

def Laws.fold_ascii():
  {==}

def Laws.fold_sharp_s():
  {==}

def Laws.fold_dotted_i():
  {==}

def Laws.fold_sigma():
  {==}

def Laws.nfc_empty():
  {==}

def Laws.graphemes_empty():
  {==}

def Laws.nfc_part0():
  {==}

def Laws.nfd_part0():
  {==}

def Laws.nfc_part0_order():
  {==}

def Laws.nfd_part0_order():
  {==}

def Laws.nfc_exclusion():
  {==}

def Laws.nfd_exclusion():
  {==}

def Laws.nfc_hangul():
  {==}

def Laws.nfd_hangul():
  {==}

def Laws.nfc_part2_order():
  {==}

def Laws.nfd_part2_order():
  {==}

def Laws.nfc_part3():
  {==}

def Laws.nfd_part3():
  {==}

def Laws.nfc_part4():
  {==}

def Laws.nfd_part4():
  {==}

def Laws.nfc_part5():
  {==}

def Laws.nfd_part5():
  {==}

def Laws.graphemes_crlf():
  {==}

def Laws.graphemes_hangul():
  {==}

def Laws.graphemes_flags():
  {==}

def Laws.graphemes_emoji_zwj():
  {==}

def Laws.graphemes_conjunct():
  {==}

def Laws.graphemes_conjunct_break():
  {==}
