import Base
import ./files.bend as Fs
import ./LAWS.bend as Laws

def Laws.normalize_empty():
  {==}

def Laws.normalize_root():
  {==}

def Laws.normalize_dot():
  {==}

def Laws.normalize_parent():
  {==}

def Laws.normalize_duplicate_separators():
  {==}

def Laws.normalize_relative():
  {==}

def Laws.normalize_relative_parents():
  {==}

def Laws.join_absolute():
  {==}

def Laws.parent_file():
  {==}

def Laws.file_name_root():
  {==}

def Laws.extension_dotfile():
  {==}

def Laws.extension_multi():
  {==}
