import Base
import ./LAWS.bend as Laws

def Laws.utf8_empty():
  {==}

def Laws.utf8_decode_empty():
  {==}

def Laws.utf8_ascii():
  {==}

def Laws.utf8_two():
  {==}

def Laws.utf8_three():
  {==}

def Laws.utf8_four():
  {==}

def Laws.utf8_roundtrip():
  {==}

def Laws.utf8_bad_lead():
  {==}

def Laws.utf8_reprocess():
  {==}

def Laws.utf8_truncated():
  {==}

def Laws.utf8_overlong():
  {==}

def Laws.utf8_surrogate():
  {==}
