import Base
import ./encoding.bend as Hex
import ./LAWS.bend as Laws

def Laws.encode_empty():
  {==}

def Laws.decode_empty():
  {==}

def Laws.decode_odd():
  {==}

def Laws.utf8_ascii():
  {==}

def Laws.utf8_two():
  {==}

def Laws.utf8_three():
  {==}

def Laws.utf8_four():
  {==}

def Laws.utf8_roundtrip():
  {==}

def Laws.utf8_bad_lead():
  {==}

def Laws.utf8_reprocess():
  {==}

def Laws.utf8_truncated():
  {==}

def Laws.utf8_overlong():
  {==}

def Laws.utf8_surrogate():
  {==}
